#!/usr/bin/env python3

import os
import sys
import argparse
from utils import *

def get_path(arg_name):
    parser = argparse.ArgumentParser()
    parser.add_argument(
        arg_name,
        nargs='?',
        default=os.getcwd(),
        help="System path for which you want directory listing"
    )

    args = parser.parse_args()
    return str(args.directory_path)

def display_file_infos(file_infos):

    def prepare_title(title):
        title_len = len(title)

        if title_len > 32:
            return title[0:29] + '...'
        else:
            return title

    def prepare_owner_and_group(owner, group):
        return "{}:{}".format(owner, group)

    title_pad = max(len(title) for title in map(lambda x: x.title, file_infos))
    title_pad = title_pad if title_pad < 32 else 32

    printable = ""
    format_str = "{} {:" + str(title_pad) + "} {} {:>8} {:>4} {}"

    for file_inf in file_infos:
        _t_str = format_str.format(
            file_inf.type,
            prepare_title(file_inf.title),
            file_inf.modtime,
            file_inf.size,
            file_inf.permission,
            prepare_owner_and_group(file_inf.owner, file_inf.group)
        )

        if len(printable) == 0:
            printable = _t_str
        else:
            printable += "\n" + _t_str

    print(printable)


if __name__ == '__main__':
    try:
        directory_path = get_path('directory_path')
        files = check_and_get_file_infos(directory_path)
        display_file_infos(files)

    except Exception as e:
        exit(e)
